[package]
name = "decimal-maths"
version = "0.0.1"
license = "MIT"
edition = "2021"

[dependencies]
radix-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.2.0" }
radix-common-derive = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.2.0" }

[lib]
