[package]
name = "decimal-maths"
version = "0.0.1"
license = "MIT"
edition = "2021"

[dependencies]
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }

[lib]
